### PR TITLE
Remove auto-generated cabal files

### PR DESCRIPTION
**Pull request by domenkozar**
Currently I get warnings with stack that these files were modified and hpack won't regenerate them.

### CODE REVIEW

**Comment by domenkozar** [comment]
@jkarni ready for review.

**Comment by jkarni** [comment]
The problem with removing the cabal files is that someone who is not using stack won't be able to run this!

**Comment by domenkozar** [comment]
They would need to run `hpack` first. Is committing generated cabal files standard practice with hpack?

**Comment by domenkozar** [comment]
@jkarni it's your package, I think other changes are needed, but we can go with committed cabal files or not. Let me know.

**Comment by domenkozar** [comment]
Incorporated into #7

**Pull request closed without merging**
